# SUPCON Factory Layout Configuration for Multiple Lines
# This file defines the physical layout and parameters of the factory simulation

factory:
  name: "SUPCON AdventureX NLDF"
  description: "自然语言驱动智能制造仿真工厂"

# KPI计算权重 (Global)
kpi_weights:
  production_efficiency: 0.40  # 生产效率 40%
  cost_control: 0.30           # 成本控制 30%
  robustness: 0.30             # 鲁棒性 30%

# 系统性能参数 (Global)
system:
  status_publish_interval: 10.0  # 状态发布间隔 (秒)
  simulation_step_size: 0.1      # 仿真步长 (秒)
  max_concurrent_orders: 20      # 最大并发订单数

warehouses:
  - id: "RawMaterial"
    position: [0, 20]
    interacting_points: [P0]
  - id: "Warehouse"
    position: [95, 20]
    interacting_points: [P9]

order_generator:
  generation_interval_range: [10, 10]
  quantity_weights: {1: 0.4, 2: 0.3, 3: 0.2, 4: 0.07, 5: 0.03}
  product_distribution: {P1: 0.6, P2: 0.3, P3: 0.1}
  priority_distribution: {low: 0.7, medium: 0.25, high: 0.05}
  deadline_multipliers: {low: 3.0, medium: 2.0, high: 1.5}
  theoretical_production_times: {P1: 160, P2: 200, P3: 250}

production_lines:
  - name: "line1"
    stations:
      - id: "StationA"
        position: [15, 20]
        buffer_size: 2
        processing_times:
          P1: [5, 5]
          P2: [5, 5]
          P3: [5, 5]
        interacting_points: [P1]

      - id: "StationB"
        position: [35, 20]
        buffer_size: 2
        processing_times:
          P1: [5, 5]
          P2: [5, 5]
          P3: [5, 5]
        interacting_points: [P3]

      - id: "StationC"
        position: [55, 20]
        buffer_size: 2
        processing_times:
          P1: [5, 5]
          P2: [5, 5]
          P3: [5, 5]
        interacting_points: [P5]

      - id: "QualityCheck"
        position: [75, 20]
        buffer_size: 2
        processing_times:
          P1: [5, 5]
          P2: [5, 5]
          P3: [5, 5]
        output_buffer_capacity: 4
        interacting_points: [P7, P8]
        # pass_threshold: 99
        # scrap_threshold: 98
        
    agvs:
      - id: "AGV_1"
        position: [10, 10]
        path_points:
          P0: [5, 15]
          P1: [12, 15]
          P2: [25, 15]
          P3: [32, 15]
          P4: [45, 15]
          P5: [52, 15]
          P6: [65, 10]
          P7: [72, 15]
          P8: [80, 15]
          P9: [95, 15]
          P10: [10, 10]
        speed_mps: 2.0
        battery_level: 50.0
        payload_capacity: 2
        low_battery_threshold: 10.0
        charging_point: P10
        charging_speed: 3.33
        battery_consumption_per_meter: 0.1
        battery_consumption_per_action: 0.5
      - id: "AGV_2"
        position: [10, 30]
        path_points:
          P0: [5, 25]
          P1: [12, 25]
          P2: [25, 25]
          P3: [32, 25]
          P4: [45, 25]
          P5: [52, 25]
          P6: [65, 25]
          P7: [72, 25]
          P8: [80, 25]
          P9: [95, 25]
          P10: [10, 30]
        speed_mps: 2.0
        battery_level: 50.0
        payload_capacity: 2
        low_battery_threshold: 10.0
        charging_point: P10
        charging_speed: 3.33
        battery_consumption_per_meter: 0.1
        battery_consumption_per_action: 0.5
    agv_operations:
      AGV_1:
        P0: {device: "RawMaterial", operations: ["load"]}
        P1: {device: "StationA", operations: ["unload", "load"]}
        P2: {device: "Conveyor_AB", operations: ["load"]}
        P3: {device: "StationB", operations: ["unload", "load"]}
        P4: {device: "Conveyor_BC", operations: ["load"]}
        P5: {device: "StationC", operations: ["unload", "load"]}
        P6: {device: "Conveyor_CQ", buffer: "lower", operations: ["load"]}
        P7: {device: "QualityCheck", buffer: "buffer", operations: ["unload"]}
        P8: {device: "QualityCheck", buffer: "output_buffer", operations: ["load"]}
        P9: {device: "Warehouse", operations: ["unload"]}
      AGV_2:
        P0: {device: "RawMaterial", operations: ["load"]}
        P1: {device: "StationA", operations: ["unload", "load"]}
        P2: {device: "Conveyor_AB", operations: ["load"]}
        P3: {device: "StationB", operations: ["unload", "load"]}
        P4: {device: "Conveyor_BC", operations: ["load"]}
        P5: {device: "StationC", operations: ["unload", "load"]}
        P6: {device: "Conveyor_CQ", buffer: "upper", operations: ["load"]}
        P7: {device: "QualityCheck", buffer: "buffer", operations: ["unload"]}
        P8: {device: "QualityCheck", buffer: "output_buffer", operations: ["load"]}
        P9: {device: "Warehouse", operations: ["unload"]}
    conveyors:
      - id: "Conveyor_AB"
        position: [25, 20]
        transfer_time: 5.0
        capacity: 3
        interacting_points: [P2]
      - id: "Conveyor_BC"
        position: [45, 20]
        transfer_time: 5.0
        capacity: 3
        interacting_points: [P4]
      - id: "Conveyor_CQ"
        position: [65, 20]
        transfer_time: 5.0
        main_capacity: 4
        upper_capacity: 2
        lower_capacity: 2
        interacting_points: [P6]

    fault_system:
      fault_injection_interval: [120, 180]
      auto_recovery_time: [600, 1800]
      device_relationships:
        StationA: ["StationB", "AGV_1"]
        StationB: ["StationA", "StationC", "AGV_1", "AGV_2"]
        StationC: ["StationB", "QualityCheck", "AGV_2"]
        QualityCheck: ["StationC"]
        AGV_1: ["StationA", "StationB"]
        AGV_2: ["StationB", "StationC"]

  - name: "line2"
    stations:
      - id: "StationA"
        position: [15, 60] # Changed Y coordinate
        buffer_size: 3
        processing_times: {P1: [5, 5], P2: [5, 5], P3: [5, 5]}
        interacting_points: [P1]
      - id: "StationB"
        position: [35, 60] # Changed Y coordinate
        buffer_size: 3
        processing_times: {P1: [5, 5], P2: [5, 5], P3: [5, 5]}
        interacting_points: [P3]
      - id: "StationC"
        position: [55, 60] # Changed Y coordinate
        buffer_size: 3
        processing_times: {P1: [5, 5], P2: [5, 5], P3: [5, 5]}
        interacting_points: [P5]
      - id: "QualityCheck"
        position: [75, 60] # Changed Y coordinate
        buffer_size: 1
        processing_times: {P1: [5, 5], P2: [5, 5], P3: [5, 5]}
        output_buffer_capacity: 4
        interacting_points: [P7, P8]
    agvs:
      - id: "AGV_1"
        position: [10, 50] # Changed Y coordinate
        path_points:
          P0: [5, 55]
          P1: [12, 55]
          P2: [25, 55]
          P3: [32, 55]
          P4: [45, 55]
          P5: [52, 55]
          P6: [65, 50]
          P7: [72, 55]
          P8: [80, 55]
          P9: [95, 55]
          P10: [10, 50]
        speed_mps: 2.0
        battery_level: 50.0
        payload_capacity: 2
        low_battery_threshold: 10.0
        charging_point: P10
        charging_speed: 3.33
        battery_consumption_per_meter: 0.1
        battery_consumption_per_action: 0.5
      - id: "AGV_2"
        position: [10, 70] # Changed Y coordinate
        path_points:
          P0: [5, 65]
          P1: [12, 65]
          P2: [25, 65]
          P3: [32, 65]
          P4: [45, 65]
          P5: [52, 65]
          P6: [65, 65]
          P7: [72, 65]
          P8: [80, 65]
          P9: [95, 65]
          P10: [10, 70]
        speed_mps: 2.0
        battery_level: 50.0
        payload_capacity: 2
        low_battery_threshold: 10.0
        charging_point: P10
        charging_speed: 3.33
        battery_consumption_per_meter: 0.1
        battery_consumption_per_action: 0.5
    agv_operations:
      AGV_1:
        P0: {device: "RawMaterial", operations: ["load"]}
        P1: {device: "StationA", operations: ["unload", "load"]}
        P2: {device: "Conveyor_AB", operations: ["load"]}
        P3: {device: "StationB", operations: ["unload", "load"]}
        P4: {device: "Conveyor_BC", operations: ["load"]}
        P5: {device: "StationC", operations: ["unload", "load"]}
        P6: {device: "Conveyor_CQ", buffer: "lower", operations: ["load"]}
        P7: {device: "QualityCheck", buffer: "buffer", operations: ["unload"]}
        P8: {device: "QualityCheck", buffer: "output_buffer", operations: ["load"]}
        P9: {device: "Warehouse", operations: ["unload"]}
      AGV_2:
        P0: {device: "RawMaterial", operations: ["load"]}
        P1: {device: "StationA", operations: ["unload", "load"]}
        P2: {device: "Conveyor_AB", operations: ["load"]}
        P3: {device: "StationB", operations: ["unload", "load"]}
        P4: {device: "Conveyor_BC", operations: ["load"]}
        P5: {device: "StationC", operations: ["unload", "load"]}
        P6: {device: "Conveyor_CQ", buffer: "upper", operations: ["load"]}
        P7: {device: "QualityCheck", buffer: "buffer", operations: ["unload"]}
        P8: {device: "QualityCheck", buffer: "output_buffer", operations: ["load"]}
        P9: {device: "Warehouse", operations: ["unload"]}
    conveyors:
      - id: "Conveyor_AB"
        position: [25, 60] # Changed Y coordinate
        transfer_time: 5.0
        capacity: 3
        interacting_points: [P2]
      - id: "Conveyor_BC"
        position: [45, 60] # Changed Y coordinate
        transfer_time: 5.0
        capacity: 3
        interacting_points: [P4]
      - id: "Conveyor_CQ"
        position: [65, 60] # Changed Y coordinate
        transfer_time: 5.0
        main_capacity: 4
        upper_capacity: 2
        lower_capacity: 2
        interacting_points: [P6]
    fault_system:
      fault_injection_interval: [120, 180]
      auto_recovery_time: [600, 1800]
      device_relationships:
        StationA: ["StationB", "AGV_1"]
        StationB: ["StationA", "StationC", "AGV_1", "AGV_2"]
        StationC: ["StationB", "QualityCheck", "AGV_2"]
        QualityCheck: ["StationC"]
        AGV_1: ["StationA", "StationB"]
        AGV_2: ["StationB", "StationC"]

  - name: "line3"
    stations:
      - id: "StationA"
        position: [15, 100] # Changed Y coordinate
        buffer_size: 3
        processing_times: {P1: [5, 5], P2: [5, 5], P3: [5, 5]}
        interacting_points: [P1]
      - id: "StationB"
        position: [35, 100] # Changed Y coordinate
        buffer_size: 3
        processing_times: {P1: [5, 5], P2: [5, 5], P3: [5, 5]}
        interacting_points: [P3]
      - id: "StationC"
        position: [55, 100] # Changed Y coordinate
        buffer_size: 3
        processing_times: {P1: [5, 5], P2: [5, 5], P3: [5, 5]}
        interacting_points: [P5]
      - id: "QualityCheck"
        position: [75, 100] # Changed Y coordinate
        buffer_size: 1
        processing_times: {P1: [5, 5], P2: [5, 5], P3: [5, 5]}
        output_buffer_capacity: 4
        interacting_points: [P7, P8]
    agvs:
      - id: "AGV_1"
        position: [10, 90] # Changed Y coordinate
        path_points:
          P0: [5, 95]
          P1: [12, 95]
          P2: [25, 95]
          P3: [32, 95]
          P4: [45, 95]
          P5: [52, 95]
          P6: [65, 90]
          P7: [72, 95]
          P8: [80, 95]
          P9: [95, 95]
          P10: [10, 90]
        speed_mps: 2.0
        battery_level: 50.0
        payload_capacity: 2
        low_battery_threshold: 10.0
        charging_point: P10
        charging_speed: 3.33
        battery_consumption_per_meter: 0.1
        battery_consumption_per_action: 0.5
      - id: "AGV_2"
        position: [10, 110] # Changed Y coordinate
        path_points:
          P0: [5, 105]
          P1: [12, 105]
          P2: [25, 105]
          P3: [32, 105]
          P4: [45, 105]
          P5: [52, 105]
          P6: [65, 105]
          P7: [72, 105]
          P8: [80, 105]
          P9: [95, 105]
          P10: [10, 110]
        speed_mps: 2.0
        battery_level: 50.0
        payload_capacity: 2
        low_battery_threshold: 10.0
        charging_point: P10
        charging_speed: 3.33
        battery_consumption_per_meter: 0.1
        battery_consumption_per_action: 0.5
    agv_operations:
      AGV_1:
        P0: {device: "RawMaterial", operations: ["load"]}
        P1: {device: "StationA", operations: ["unload", "load"]}
        P2: {device: "Conveyor_AB", operations: ["load"]}
        P3: {device: "StationB", operations: ["unload", "load"]}
        P4: {device: "Conveyor_BC", operations: ["load"]}
        P5: {device: "StationC", operations: ["unload", "load"]}
        P6: {device: "Conveyor_CQ", buffer: "lower", operations: ["load"]}
        P7: {device: "QualityCheck", buffer: "buffer", operations: ["unload"]}
        P8: {device: "QualityCheck", buffer: "output_buffer", operations: ["load"]}
        P9: {device: "Warehouse", operations: ["unload"]}
      AGV_2:
        P0: {device: "RawMaterial", operations: ["load"]}
        P1: {device: "StationA", operations: ["unload", "load"]}
        P2: {device: "Conveyor_AB", operations: ["load"]}
        P3: {device: "StationB", operations: ["unload", "load"]}
        P4: {device: "Conveyor_BC", operations: ["load"]}
        P5: {device: "StationC", operations: ["unload", "load"]}
        P6: {device: "Conveyor_CQ", buffer: "upper", operations: ["load"]}
        P7: {device: "QualityCheck", buffer: "buffer", operations: ["unload"]}
        P8: {device: "QualityCheck", buffer: "output_buffer", operations: ["load"]}
        P9: {device: "Warehouse", operations: ["unload"]}
    conveyors:
      - id: "Conveyor_AB"
        position: [25, 100] # Changed Y coordinate
        transfer_time: 5.0
        capacity: 3
        interacting_points: [P2]
      - id: "Conveyor_BC"
        position: [45, 100] # Changed Y coordinate
        transfer_time: 5.0
        capacity: 3
        interacting_points: [P4]
      - id: "Conveyor_CQ"
        position: [65, 100] # Changed Y coordinate
        transfer_time: 5.0
        main_capacity: 4
        upper_capacity: 2
        lower_capacity: 2
        interacting_points: [P6]
    fault_system:
      fault_injection_interval: [120, 180]
      auto_recovery_time: [600, 1800]
      device_relationships:
        StationA: ["StationB", "AGV_1"]
        StationB: ["StationA", "StationC", "AGV_1", "AGV_2"]
        StationC: ["StationB", "QualityCheck", "AGV_2"]
        QualityCheck: ["StationC"]
        AGV_1: ["StationA", "StationB"]
        AGV_2: ["StationB", "StationC"] 